%-------------------------------------------
%
%       P4-EFM-Transitorios hidraulicos
%
%-------------------------------------------

%Golpe d'ariete curt

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Yago\OneDrive - Universitat Politècnica de Catalunya\Q6\EFM\Practicas\P4\M12-xemeneia.xlsx
%    Worksheet: xemeneia curt
%
% Auto-generated by MATLAB on 02-May-2023 17:00:26

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "xemeneia curt";
opts.DataRange = "A3:C403";

% Specify column names and types
opts.VariableNames = ["Var1", "times1", "PresinbargP_Ariete"];
opts.SelectedVariableNames = ["times1", "PresinbargP_Ariete"];
opts.VariableTypes = ["char", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\Yago\OneDrive - Universitat Politècnica de Catalunya\Q6\EFM\Practicas\P4\M12-xemeneia.xlsx", opts, "UseExcel", false);

%% Convert to output type
times1 = tbl.times1;
PresinbargP_Ariete1 = tbl.PresinbargP_Ariete;

%% Clear temporary variables
clear opts tbl

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "xemeneia llarg";
opts.DataRange = "A3:C495";

% Specify column names and types
opts.VariableNames = ["Var1", "times1", "PresinbargP_Ariete"];
opts.SelectedVariableNames = ["times1", "PresinbargP_Ariete"];
opts.VariableTypes = ["char", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\Yago\OneDrive - Universitat Politècnica de Catalunya\Q6\EFM\Practicas\P4\M12-xemeneia.xlsx", opts, "UseExcel", false);

%% Convert to output type
times2 = tbl.times1;
PresinbargP_Ariete2 = tbl.PresinbargP_Ariete;

%% Clear temporary variables
clear opts tbl

% Plotting
nexttile
plot(times1,PresinbargP_Ariete1)
title('Cop ariet curt','Interpreter','latex')
xlabel('time (s)','Interpreter','latex')
ylabel('p (barg)','Interpreter','latex')

nexttile
plot(times2,PresinbargP_Ariete2)
title('Cop ariet llarg','Interpreter','latex')
xlabel('time (s)','Interpreter','latex')
ylabel('p (barg)','Interpreter','latex')